---
- name: Converge
  hosts: all
  become: true

  vars:
    wallabag_container_user: root
    wallabag_mysql_root_password: wallaroot
    wallabag_db_user: wallabag
    wallabag_db_password: wallabag
    

  roles:
    - role: iasensio.wallabag
