---
- name: Converge
  hosts: all
  become: true

  vars:
    wallabag_container_user: root
    wallabag_mysql_root_password: wallaroot
    wallabag_db_user: wallabag
    wallabag_db_password: wallabag
    wallabag_mailer_dsn: "smtp://127.0.0.1"
    wallabag_from_email: "wallabag@example.com"

    

  roles:
    - role: iasensio.wallabag
